---
title: "Esports Psychological Momentum Analysis"
format: html
editor: visual
runtime: shiny
page-layout: full
---

## Load Libraries and Setup

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(plotly)
library(ggplot2)
library(reshape2)
library(glue)
library(DT)
library(dplyr)
library(brms)
library(tidybayes)
library(lme4)
library(shiny)
library(caret)
library(yardstick)
library(randomForest)
```

------------------------------------------------------------------------

## Data Overview

```{r}
url_list <- list(
  Rocket_League = "https://github.com/rstienstra1/esports_psych_analysis/releases/download/v1.0/Rocket_League.xlsx",
  Rainbow_6 = "https://github.com/rstienstra1/esports_psych_analysis/releases/download/v1.0/Rainbow_6.xlsx"
)

dataframes <- lapply(names(url_list), function(game) {
  temp <- tempfile(fileext = ".xlsx")
  download.file(url_list[[game]], temp, mode = "wb")
  readxl::read_excel(temp) %>% dplyr::mutate(game = game)
})

all_data <- dplyr::bind_rows(dataframes)
```

------------------------------------------------------------------------

## Hypothesis 1: Bayesian Logistic Regression (Rainbow 6)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rainbow_6_h1/bayesian_log_r6.R")
```

## Hypothesis 1: Bayesian Logistic Regression (Rocket League)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rocket_league_h1/bayesian_log_rocket.R")
```

------------------------------------------------------------------------

## Hypothesis 1: Classic Logistic Regression (Rainbow 6)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rainbow_6_h1/classic_log_r6.R")
```

## Hypothesis 1: Classic Logistic Regression (Rocket League)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rocket_league_h1/classic_log_rocket.R")
```

------------------------------------------------------------------------

## Hypothesis 1: Random Forest Model (Rainbow 6)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rainbow_6_h1/randomForest_r6.R")
```

## Hypothesis 1: Random Forest Model (Rocket League)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rocket_league_h1/randomForest_rocket.R")
```

------------------------------------------------------------------------

## Hypothesis 1: Exploratory Visualizations (Rainbow 6)

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rainbow_6_h1/exploratory_visuals_r6.R")
```

------------------------------------------------------------------------

## Hypothesis 1: Proportion and Chi-Square Testing

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rainbow_6_h1/stats_r6.R")
```

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_1/rocket_league_h1/stats_rocket.R")
```

------------------------------------------------------------------------

## Hypothesis 2: Psychological Momentum & Comebacks

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_2/hypothesis_2_visualizations_v2.R")
```

------------------------------------------------------------------------

## Hypothesis 3: Resilience by Seeding Strength

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_3/rainbow_rank.R")
```

```{r}
source("https://raw.githubusercontent.com/rstienstra1/esports_psych_analysis/refs/tags/v1.0/hypothesis_3/rocket_rank.R")
```

------------------------------------------------------------------------

## Game Count Overview

```{r}
plot_ly(all_data %>% count(game), x = ~game, y = ~n, type = "bar")
```

------------------------------------------------------------------------

## Explore Raw Data

```{r}
DT::datatable(all_data, options = list(pageLength = 5))
```
